apiVersion: 1

datasources:
  - name: "Prometheus"
    type: prometheus
    access: proxy
    uid: ds-prometheus
    url: http://prometheus:9090
    editable: false
    jsonData:
      timeInterval: 2m
